import { Inter } from "next/font/google";
import "./globals.css";
import LeftComponent from "./components/leftComponent";
import { NavbarWithSearch } from "./digitalflake/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarWithSearch />
        <div className="flex justify-start">
          <LeftComponent />
          {children}
        </div>
      </body>
    </html>
  );
}
